
# https://csandker.io
#
#
#
title: csandker.io
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog
baseurl: "/" # the subpath of my site
url: "https://csandker.io/" # the base hostname & protocol

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Reading Files
include:
  - _pages

twitter:
  user: 0xcsandker
  url: "https://twitter.com/0xcsandker"

mastodon:
  user: 0xcsandker
  url: "https://infosec.exchange/@0xcsandker"

github:
  user: csandker
  url: "https://github.com/csandker"
  site_repo_name: "csandker.github.io"

feed:
  tagname: RSS Feed
  url: "/feed.xml"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
